---
- name: generate cmpt json
  template:
    src=cmpt.json.j2
    dest={{ sensu_config_path }}/conf.d/cmpt.json
    owner=sensu
    group=sensu
    mode=0640
    backup=yes
  notify:
    - restart sensu client

- name: generate sudoers for sensu on cmpt
  template:
    src=sensu_sudoers_cmpt.json.j2
    dest=/etc/sudoers.d/sensu_cmpt
    owner=root
    group=root
    mode=0440
    backup=yes
