---
- set_fact:
    sensu_rpm_version: "sensu-0.22.0-1.el7ost.noarch.rpm"
  when: sensu_use_upstream_version is not defined or sensu_use_upstream_version == false

# Using the upstream version will make you use SSL and self-signed certificates (Will change later).
- set_fact:
    sensu_rpm_version: "sensu-0.22.1-1.x86_64.rpm"
  when: sensu_use_upstream_version is defined and sensu_use_upstream_version == true

- set_fact:
    sensu_server_rabbitmq_port: 5672
  when: sensu_api_ssl is not defined or sensu_api_ssl == false

- set_fact:
    sensu_server_rabbitmq_port: 5671
  when: sensu_api_ssl is defined and sensu_api_ssl == true

- name: Verify proper CDN registration
  command: /usr/sbin/subscription-manager identity
  register: command_result
  changed_when: "command_result.rc != 0"
  when: sensu_use_local_repo is not defined or sensu_use_local_repo == false
  
- name: Copy ALL of the required common rpms
  copy:
    src=rpms/
    dest=/var/tmp/rpms/
    mode=0750
  when: sensu_use_local_repo is defined and sensu_use_local_repo == true

- name: Monitoring for Openstack (All installs)
  yum: name={{ item }} state=present
  with_items:
    - /var/tmp/rpms/common/osops-tools-monitoring-oschecks-0.1-0.5_1.dd7ca5cgit.el7.noarch.rpm
    - /var/tmp/rpms/common/perl-Class-Accessor-0.34-1.el7eng.noarch.rpm
    - /var/tmp/rpms/common/perl-Config-Tiny-2.14-7.el7.noarch.rpm
    - /var/tmp/rpms/common/perl-Math-Calc-Units-1.07-6.el7.it.noarch.rpm
    - /var/tmp/rpms/common/perl-Nagios-Plugin-0.36-6.el7.it.noarch.rpm

- name: Install Sensu Pre-Reqs (local install)
  yum: name={{ item }} state=present
  with_items:
    - /var/tmp/rpms/common/nagios-plugins-ping-2.0.1-1.2.el7.x86_64.rpm
    - /var/tmp/rpms/common/nagios-plugins-2.0.1-1.2.el7.x86_64.rpm
    - /var/tmp/rpms/common/nagios-common-3.5.1-6.el7.x86_64.rpm
    - /var/tmp/rpms/common/rubygem-amqp-1.5.0-2.el7ost.noarch.rpm
    - /var/tmp/rpms/common/rubygem-amq-protocol-1.9.2-3.el7ost.noarch.rpm
    - /var/tmp/rpms/common/rubygem-async_sinatra-1.1.0-1.el7ost.noarch.rpm
    - /var/tmp/rpms/common/rubygem-childprocess-0.5.5-3.el7ost.noarch.rpm
    - /var/tmp/rpms/common/rubygem-daemons-1.1.9-3.el7ost.noarch.rpm
    - /var/tmp/rpms/common/rubygem-em-redis-unified-0.5.0-1.el7ost.noarch.rpm
    - /var/tmp/rpms/common/rubygem-em-worker-0.0.2-2.el7ost.noarch.rpm
    - /var/tmp/rpms/common/rubygem-eventmachine-1.0.6-2.el7ost.x86_64.rpm
    - /var/tmp/rpms/common/rubygem-ffi-1.9.3-1.el7ost.x86_64.rpm
    - /var/tmp/rpms/common/rubygem-multi_json-1.10.1-1.el7ost.noarch.rpm
    - /var/tmp/rpms/common/rubygem-rack-1.5.2-4.el7ost.noarch.rpm
    - /var/tmp/rpms/common/rubygem-rack-protection-1.5.3-2.el7ost.noarch.rpm
    - /var/tmp/rpms/common/rubygem-sensu-em-2.4.0-1.el7ost.x86_64.rpm
    - /var/tmp/rpms/common/rubygem-sensu-extension-1.0.0-1.el7ost.noarch.rpm
    - /var/tmp/rpms/common/rubygem-sensu-extensions-1.0.0-1.el7ost.noarch.rpm
    - /var/tmp/rpms/common/rubygem-sensu-logger-1.0.0-1.el7ost.noarch.rpm
    - /var/tmp/rpms/common/rubygem-sensu-settings-1.2.0-1.el7ost.noarch.rpm
    - /var/tmp/rpms/common/rubygem-sensu-spawn-1.1.0-2.el7ost.noarch.rpm
    - /var/tmp/rpms/common/rubygem-sensu-transport-2.4.0-3.el7ost.noarch.rpm
    - /var/tmp/rpms/common/rubygem-sinatra-1.4.5-3.el7ost.noarch.rpm
    - /var/tmp/rpms/common/rubygem-thin-1.6.2-5.el7ost.x86_64.rpm
    - /var/tmp/rpms/common/rubygem-tilt-1.4.1-3.el7ost.noarch.rpm
    - /var/tmp/rpms/common/rubygem-uuidtools-2.1.5-2.el7ost.noarch.rpm
    - /var/tmp/rpms/common/ruby-2.0.0.598-25.el7_1.x86_64.rpm
    - /var/tmp/rpms/common/ruby-libs-2.0.0.598-25.el7_1.x86_64.rpm
    - /var/tmp/rpms/common/ruby-irb-2.0.0.598-25.el7_1.noarch.rpm
    - /var/tmp/rpms/common/rubygem-bigdecimal-1.2.0-25.el7_1.x86_64.rpm
    - /var/tmp/rpms/common/rubygem-io-console-0.4.2-25.el7_1.x86_64.rpm
    - /var/tmp/rpms/common/rubygem-json-1.7.7-25.el7_1.x86_64.rpm
    - /var/tmp/rpms/common/rubygem-psych-2.0.0-25.el7_1.x86_64.rpm
    - /var/tmp/rpms/common/rubygem-rdoc-4.0.0-25.el7_1.noarch.rpm
    - /var/tmp/rpms/common/rubygems-2.0.14-25.el7_1.noarch.rpm
    - /var/tmp/rpms/common/perl-Class-Accessor-0.34-1.el7eng.noarch.rpm
    - /var/tmp/rpms/common/perl-Config-Tiny-2.14-7.el7.noarch.rpm
    - /var/tmp/rpms/common/perl-Math-Calc-Units-1.07-6.el7.it.noarch.rpm
    - /var/tmp/rpms/common/perl-Nagios-Plugin-0.36-6.el7.it.noarch.rpm
    - /var/tmp/rpms/common/perl-Module-Implementation-0.06-6.el7.noarch.rpm
    - /var/tmp/rpms/common/perl-Module-Runtime-0.013-4.el7.noarch.rpm
    - /var/tmp/rpms/common/perl-Params-Validate-1.08-4.el7.x86_64.rpm
    - /var/tmp/rpms/common/perl-Try-Tiny-0.12-2.el7.noarch.rpm
  when: sensu_use_local_repo is defined and sensu_use_local_repo == true

- name: Install Sensu rpm (local install)
  yum: name={{ item }} state=present
  with_items:
    - /var/tmp/rpms/common/{{ sensu_rpm_version }}
  when: sensu_use_local_repo is defined and sensu_use_local_repo == true

- name: Install Sensu Pre-Reqs (CDN install)
  yum: name={{ item }} enablerepo=rhel-7-server-openstack-7.0-optools-rpms state=present
  with_items:
    - nagios-plugins-ping
    - nagios-plugins
    - rubygem-amqp
    - rubygem-amq-protocol
    - rubygem-async_sinatra
    - rubygem-childprocess
    - rubygem-daemons
    - rubygem-em-redis-unified
    - rubygem-em-worker
    - rubygem-eventmachine
    - rubygem-ffi
    - rubygem-multi_json
    - rubygem-rack
    - rubygem-rack-protection
    - rubygem-sensu-em
    - rubygem-sensu-extension
    - rubygem-sensu-logger
    - rubygem-sensu-settings
    - rubygem-sensu-spawn
    - rubygem-sensu-transport
    - rubygem-sinatra
    - rubygem-thin
    - rubygem-tilt
    - rubygem-uuidtools
  when: sensu_use_local_repo is not defined or sensu_use_local_repo == false

- name: Install Sensu (CDN install)
  yum: name={{ item }} enablerepo=rhel-7-server-openstack-7.0-optools-rpms state=present
  with_items:
    - sensu
  when: sensu_use_local_repo is not defined or sensu_use_local_repo == false
