---
- name: generate ctrl json
  template:
    src=ctrl.json.j2
    dest={{ sensu_config_path }}/conf.d/ctrl.json
    owner=sensu
    group=sensu
    mode=0640
    backup=yes
  notify:
    - restart sensu client

- name: generate sudoers for sensu on controllers
  template:
    src=sensu_sudoers_ctrl.json.j2
    dest=/etc/sudoers.d/sensu_ctrl
    owner=root
    group=root
    mode=0440
    backup=yes

