---
# tasks/ssl_generate.yml: Generate SSL data and stash to dynamic
# data store for deployment to clients

  - name: Ensure Sensu SSL directory exists
    file:
      dest: "{{ sensu_config_path }}/ssl"
      state: directory
      owner: "{{ sensu_user_name }}"
      group: "{{ sensu_group_name }}"

  - name: Ensure SSL generation directory exists
    file:
      dest: "{{ sensu_config_path }}/ssl_generation"
      state: directory
      owner: "{{ sensu_user_name }}"
      group: "{{ sensu_group_name }}"
    when: sensu_install_server is defined and sensu_install_server == true

  - block:

    - name: Copy the ssl_certs tarball from sensuapp.org to proper location
      copy:
        src: sensu/ssl/sensu_ssl_tool.tar
        dest: "{{ sensu_config_path }}/ssl_generation/sensu_ssl_tool.tar"

    - name: Untar the ssl_certs tarball from sensuapp.org
      shell: tar xf sensu_ssl_tool.tar
      args:
        chdir: "{{ sensu_config_path }}/ssl_generation"
        creates: "{{ sensu_config_path }}/ssl_generation/sensu_ssl_tool"
  
    - name: Generate SSL certs
      shell: ./ssl_certs.sh generate
      args:
        chdir: "{{ sensu_config_path }}/ssl_generation/sensu_ssl_tool"
        creates: "{{ sensu_config_path }}/ssl_generation/sensu_ssl_tool/server"

    when: sensu_install_server is defined and sensu_install_server == true
    become: true
    become_user: "{{ sensu_user_name }}"

  - name: Stash the Sensu SSL certs/keys
    fetch:
      src: "{{ sensu_config_path }}/ssl_generation/sensu_ssl_tool/{{ item }}"
      dest: "{{ dynamic_data_store }}"
    when: sensu_install_server is defined and sensu_install_server == true
    with_items:
      - sensu_ca/cacert.pem
      - server/cert.pem
      - server/key.pem
      - client/cert.pem
      - client/key.pem
